#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/.config/hypr/theme/walls"
LAST_WALL="$HOME/.cache/last_wallpaper.txt"
TRIGGER="$HOME/.cache/wallpaper_trigger"
INTERVAL=900 # 60 = 1min; 900 = 15min

LOCK="/tmp/hyprpaper_daemon.lock"
exec 200>$LOCK
flock -n 200 || exit 0

choose() {
    find "$WALLPAPER_DIR" -type f | shuf -n 1
}

wait_for_hyprpaper() {
    while ! hyprctl hyprpaper listpreloaded &>/dev/null; do
        sleep 0.5
    done
}

switch_wall() {
    local wp="$1"
    hyprctl hyprpaper preload "$wp"
    sleep 0.2
    hyprctl hyprpaper wallpaper ",$wp"
}

wait_for_hyprpaper

while true; do
    if [ -f "$TRIGGER" ]; then
        rm "$TRIGGER"

        if [ -f "$LAST_WALL" ]; then
            new="$(cat "$LAST_WALL")"
        else
            new="$(choose)"
        fi
    else
        new="$(choose)"
    fi


    if [ -f "$LAST_WALL" ] && [ "$new" = "$(cat "$LAST_WALL")" ]; then
        :
    else
        echo "$new" > "$LAST_WALL"
        switch_wall "$new"
    fi

    for ((i=0; i<INTERVAL; i++)); do
        [ -f "$TRIGGER" ] && break
        sleep 1
    done
done

# Run this after every change:
# systemctl --user daemon-reload && systemctl --user restart wallpaper-daemon.service && systemctl --user status wallpaper-daemon.service
